/**
 * Materialising a built map onto disk (sync spec "Write", tech spec 4.2).
 *
 * Two properties matter more than speed here.
 *
 * Minimal churn: a file is written only when its bytes actually differ, so an
 * update that changes one card leaves the other few thousand artifacts with
 * their original mtimes. Editors, watchers and `git status` all stay quiet, and
 * "greplost ran" stops being visible in the working tree.
 *
 * Bounded ownership: the writer touches exactly the structure paths
 * (`isStructurePath`) and nothing else. Files the map no longer produces — the
 * card of a deleted source file, the docs of a renamed package — are pruned,
 * and directories emptied by that pruning are removed; `config.json`, the
 * caches, `FLOWS.md`, `WORKSPACE.md` and the runtime files are invisible to it.
 * Nothing outside `<root>/.greplost/` is ever written, read or deleted.
 */

import {
  lstatSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  rmdirSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";

import { ARTIFACT_DIR, compareStrings } from "@greplost/core/schema";

import { isStructurePath, listStructurePaths } from "./artifacts.ts";

export interface WriteResult {
  /** Structure paths whose bytes changed (or that did not exist), sorted. */
  written: string[];
  /** Structure paths removed because the map no longer produces them, sorted. */
  deleted: string[];
  /** Structure paths already byte-identical on disk, left with their mtimes. */
  unchanged: number;
}

/**
 * Write `files` (artifact-relative path -> contents) under `<root>/.greplost/`,
 * pruning structure paths the map does not contain.
 *
 * Throws before touching the disk if any key is not a structure path: a bad key
 * is a defect in the producer, and acting on it is how a writer escapes the
 * artifact directory.
 */
export function writeArtifacts(root: string, files: Map<string, string>): WriteResult {
  const artifactRoot = path.resolve(root, ARTIFACT_DIR);

  for (const rel of files.keys()) {
    if (!isStructurePath(rel)) {
      throw new Error(`greplost: refusing to write ${rel}: not a structure-layer artifact path`);
    }
  }

  const written: string[] = [];
  let unchanged = 0;

  for (const rel of [...files.keys()].sort(compareStrings)) {
    const contents = files.get(rel) as string;
    const target = resolveInside(artifactRoot, rel);
    if (writeIfDifferent(artifactRoot, rel, target, contents)) written.push(rel);
    else unchanged++;
  }

  const deleted = prune(artifactRoot, files);

  return { written, deleted, unchanged };
}

/**
 * Join an artifact-relative path onto the artifact root and prove the result is
 * still inside it. `isStructurePath` already rejects `..`, absolute paths and
 * backslashes; this is the belt to that pair of braces, because the cost of
 * being wrong is a write outside `.greplost/`.
 */
function resolveInside(artifactRoot: string, rel: string): string {
  const target = path.resolve(artifactRoot, rel);
  if (target !== artifactRoot && !target.startsWith(artifactRoot + path.sep)) {
    throw new Error(`greplost: refusing to write ${rel}: outside ${ARTIFACT_DIR}/`);
  }
  return target;
}

/**
 * Write `contents` to `target` unless the file already holds exactly those
 * bytes. Returns true when the file was written.
 *
 * Whatever else is at the path goes: a directory left by a botched merge, a
 * symlink pointing somewhere else entirely (writing through it would put
 * generated bytes outside `.greplost/`), a file the process cannot read or
 * cannot open for writing. The structure layer owns this path and regenerates
 * it from source every time, so replacing it loses nothing and keeps `greplost
 * update` working on a damaged artifact directory instead of stopping there.
 * The byte comparison is only ever an optimisation.
 */
function writeIfDifferent(artifactRoot: string, rel: string, target: string, contents: string): boolean {
  const expected = Buffer.from(contents, "utf8");

  let existing: ReturnType<typeof lstatSync> | undefined;
  try {
    existing = lstatSync(target);
  } catch {
    existing = undefined;
  }

  if (existing !== undefined) {
    if (existing.isFile()) {
      try {
        if (readFileSync(target).equals(expected)) return false;
      } catch {
        // Unreadable: it cannot be compared, so it is replaced.
        discard(target);
      }
    } else {
      discard(target);
    }
  }

  ensureDirectory(artifactRoot, path.dirname(target));
  try {
    writeFileSync(target, expected);
  } catch (cause) {
    // A read-only artifact (mode 444, a stray `chmod`) is still ours to replace.
    discard(target);
    try {
      writeFileSync(target, expected);
    } catch {
      const reason = cause instanceof Error ? cause.message : String(cause);
      throw new Error(`greplost: cannot write ${ARTIFACT_DIR}/${rel}: ${reason}`);
    }
  }
  return true;
}

/**
 * Make `dir` exist, replacing anything on the way to it that is not a
 * directory. The mirror of `writeIfDifferent`'s handling of a directory
 * squatting on an artifact: a file sitting where `repo/` belongs is damage the
 * structure layer can repair, and the alternative is a raw `ENOTDIR` that
 * blocks every future update.
 *
 * The repair path only runs after the ordinary `mkdirSync` has failed, so a
 * `.greplost` that is a symlink to a real directory (which `mkdirSync`
 * happily follows) is never disturbed.
 */
function ensureDirectory(artifactRoot: string, dir: string): void {
  try {
    mkdirSync(dir, { recursive: true });
    return;
  } catch {
    // Something along the way is not a directory.
  }

  let current = artifactRoot;
  replaceIfNotDirectory(current);
  mkdirSync(current, { recursive: true });
  for (const segment of path.relative(artifactRoot, dir).split(path.sep)) {
    if (segment === "") continue;
    current = path.join(current, segment);
    replaceIfNotDirectory(current);
    mkdirSync(current, { recursive: true });
  }
}

function replaceIfNotDirectory(target: string): void {
  try {
    if (lstatSync(target).isDirectory()) return;
  } catch {
    return;
  }
  discard(target);
}

/**
 * Remove whatever is at `target`. Failure is left to the caller's own write or
 * `mkdir` to report, which can name the artifact the user actually cares about.
 */
function discard(target: string): void {
  try {
    rmSync(target, { recursive: true, force: true });
  } catch {
    // Reported by the operation this was clearing the way for.
  }
}

/**
 * Delete every structure path present under the artifact root and absent from
 * `files`, then remove the directories that emptied as a result.
 *
 * Only directories on the path of something actually deleted are considered, so
 * an empty `cache/` a user left behind is not "tidied away": the writer's remit
 * is the structure layer, not the artifact directory as a whole.
 */
function prune(artifactRoot: string, files: Map<string, string>): string[] {
  const deleted: string[] = [];
  const emptied = new Set<string>();

  for (const rel of listStructurePaths(artifactRoot)) {
    if (files.has(rel)) continue;
    try {
      // A directory squatting on a structure path is as stale as a file:
      // whatever it holds, the structure layer no longer produces this path.
      rmSync(path.join(artifactRoot, rel), { recursive: true, force: true });
    } catch (cause) {
      // Swallowing this would leave `verify` reporting the path as extra
      // forever with nothing to explain why.
      const reason = cause instanceof Error ? cause.message : String(cause);
      throw new Error(`greplost: cannot delete ${ARTIFACT_DIR}/${rel}: ${reason}`);
    }
    deleted.push(rel);
    const slash = rel.lastIndexOf("/");
    if (slash !== -1) emptied.add(rel.slice(0, slash));
  }

  // Deepest first, so `packages/x/modules/src` is gone before `packages/x/modules`
  // is tested for emptiness.
  const candidates = [...expandAncestors(emptied)].sort((a, b) => b.length - a.length || compareStrings(a, b));
  for (const rel of candidates) {
    const dir = path.join(artifactRoot, rel);
    try {
      // lstat, not stat: a symlink to a directory is a link, and removing it
      // because whatever it points at happens to be empty would be wrong.
      if (!lstatSync(dir).isDirectory()) continue;
      if (readdirSync(dir).length > 0) continue;
      rmdirSync(dir);
    } catch {
      // Already gone, or not ours to remove.
    }
  }

  return deleted.sort(compareStrings);
}

/** Every directory on the path of a pruned artifact, itself included. */
function expandAncestors(dirs: ReadonlySet<string>): Set<string> {
  const out = new Set<string>();
  for (const dir of dirs) {
    const segments = dir.split("/");
    for (let i = segments.length; i > 0; i--) out.add(segments.slice(0, i).join("/"));
  }
  return out;
}
