/**
 * greplost:render document assembly (render spec "Documents", tech spec 4.2/4.3).
 *
 * `renderArtifacts` turns one `Snapshot` plus its `SummaryCache` into every
 * markdown artifact under `.greplost/`, keyed by artifact-relative path. Pure:
 * no filesystem access, no `Date`, no environment, no absolute paths — the
 * only date that ever reaches the output is the `refreshedAt` of a semantic
 * summary, and only inside the staleness banner (tech spec 5.3, 6).
 *
 * The per-document renderers all take the same `RenderInput` and are exported
 * for callers that want one artifact; `renderArtifacts` builds the shared
 * `DocContext` once and reuses it, so a full render stays linear in the number
 * of files rather than quadratic.
 *
 * Module layout: this file owns the context and the public surface; the six
 * `docs/*.ts` modules own one document each and depend on this file for types
 * only (`import type`), which keeps the runtime import graph acyclic.
 */

import type {
  CallEdge,
  Declaration,
  FileEntry,
  FileRecord,
  GreplostConfig,
  ImportEdge,
  Manifest,
  PackageEntry,
  PackageInfo,
  Snapshot,
  SummaryCache,
} from "@greplost/core/schema";
import { compareStrings, isFileId } from "@greplost/core/schema";

import { cardPath, packageDir } from "./slug.ts";
import { buildIndex } from "./docs/index-doc.ts";
import { buildRepoMap } from "./docs/repo-map.ts";
import { buildHotspots } from "./docs/hotspots.ts";
import { buildPackageMap } from "./docs/package-map.ts";
import { buildApi } from "./docs/api.ts";
import { buildCard } from "./docs/card.ts";

export interface RenderInput {
  snapshot: Snapshot;
  summaries: SummaryCache;
}

/** The generated-by line every artifact carries under its level-1 title. */
export const GENERATED_LINE = "> Generated by greplost. Do not edit by hand; run `greplost update`.";

/**
 * Everything the document renderers need, indexed once. Held by value so a
 * document renderer is a pure function of `(ctx, target)` and never walks the
 * whole snapshot to answer a per-file question.
 */
export interface DocContext {
  snapshot: Snapshot;
  summaries: SummaryCache;
  config: GreplostConfig;
  manifest: Manifest;
  /** Copied here so the docs modules never import a value from this file. */
  generatedLine: string;
  /** Name of the package rooted at ".", or the repo's own directory-less fallback. */
  rootName: string;
  /** Every package, sorted by path. */
  packages: PackageInfo[];
  packageByName: Map<string, PackageInfo>;
  /** Repo-relative file paths, sorted, per package name. */
  filesByPackage: Map<string, string[]>;
  /** Every repo file path, sorted. */
  files: string[];
  /** Import/re-export edges leaving a file, in snapshot order. */
  importsFrom: Map<string, ImportEdge[]>;
  /** Distinct repo files importing a file, sorted. */
  importersOf: Map<string, string[]>;
  /** Call edges leaving a file (from the file itself or any symbol in it). */
  callsFrom: Map<string, CallEdge[]>;
  /** Declarations of a file, in line order. */
  declsOf: Map<string, Declaration[]>;
  /** The extracted record of a file, when the snapshot carries one. */
  recordOf: Map<string, FileRecord>;
  /** Distinct external package names imported by a package, sorted. */
  externalsOf: Map<string, string[]>;
  packageEntry(name: string): PackageEntry | undefined;
  fileEntry(file: string): FileEntry | undefined;
  packageOf(file: string): PackageInfo | undefined;
  /** Artifact path of a file's module card, or undefined when the file is unknown. */
  cardPathOf(file: string): string | undefined;
}

/** Builds the shared index. Cheap enough to call per document, linear in the snapshot. */
export function createContext(input: RenderInput): DocContext {
  const { snapshot } = input;
  const manifest = snapshot.manifest;

  const packages = [...snapshot.packages].sort((a, b) => compareStrings(a.path, b.path));
  const packageByName = new Map<string, PackageInfo>();
  for (const pkg of snapshot.packages) packageByName.set(pkg.name, pkg);

  const rootName = packages.find((p) => p.path === ".")?.name ?? packages[0]?.name ?? "repo";

  const files = Object.keys(manifest.files).sort(compareStrings);
  const filesByPackage = new Map<string, string[]>();
  for (const pkg of packages) filesByPackage.set(pkg.name, []);
  for (const file of files) {
    const pkgName = manifest.files[file]?.pkg;
    if (pkgName === undefined) continue;
    const bucket = filesByPackage.get(pkgName);
    if (bucket) bucket.push(file);
    else filesByPackage.set(pkgName, [file]);
  }

  const importsFrom = new Map<string, ImportEdge[]>();
  const importerSets = new Map<string, Set<string>>();
  const externalSets = new Map<string, Set<string>>();
  for (const edge of snapshot.imports) {
    const bucket = importsFrom.get(edge.from);
    if (bucket) bucket.push(edge);
    else importsFrom.set(edge.from, [edge]);

    if (manifest.files[edge.to] !== undefined && isFileId(edge.to)) {
      const importers = importerSets.get(edge.to);
      if (importers) importers.add(edge.from);
      else importerSets.set(edge.to, new Set([edge.from]));
    }

    if (edge.to.startsWith("ext:")) {
      const pkgName = manifest.files[edge.from]?.pkg;
      if (pkgName !== undefined) {
        const externals = externalSets.get(pkgName);
        if (externals) externals.add(edge.to.slice("ext:".length));
        else externalSets.set(pkgName, new Set([edge.to.slice("ext:".length)]));
      }
    }
  }
  const importersOf = new Map<string, string[]>();
  for (const [file, importers] of importerSets) {
    importersOf.set(file, [...importers].sort(compareStrings));
  }
  const externalsOf = new Map<string, string[]>();
  for (const pkg of packages) externalsOf.set(pkg.name, []);
  for (const [pkgName, externals] of externalSets) {
    externalsOf.set(pkgName, [...externals].sort(compareStrings));
  }

  const callsFrom = new Map<string, CallEdge[]>();
  for (const call of snapshot.calls) {
    const file = fileOfSymbol(call.from);
    const bucket = callsFrom.get(file);
    if (bucket) bucket.push(call);
    else callsFrom.set(file, [call]);
  }

  // Copied, never sorted in place: the snapshot is an input and must survive a
  // render unchanged (the determinism tests render the same object twice).
  const declsOf = new Map<string, Declaration[]>();
  const recordOf = new Map<string, FileRecord>();
  for (const record of snapshot.files) {
    recordOf.set(record.path, record);
    declsOf.set(record.path, [...record.decls]);
  }
  // A snapshot whose `symbols` cover a file with no `FileRecord` (a partial or
  // reconstructed snapshot) still gets a card.
  for (const decl of snapshot.symbols) {
    if (recordOf.has(decl.file)) continue;
    const bucket = declsOf.get(decl.file);
    if (bucket) bucket.push(decl);
    else declsOf.set(decl.file, [decl]);
  }
  for (const decls of declsOf.values()) {
    decls.sort((a, b) => a.span[0] - b.span[0] || compareStrings(a.id, b.id));
  }

  const packageOf = (file: string): PackageInfo | undefined => {
    const pkgName = manifest.files[file]?.pkg;
    return pkgName === undefined ? undefined : packageByName.get(pkgName);
  };

  return {
    snapshot,
    summaries: input.summaries,
    config: snapshot.config,
    manifest,
    generatedLine: GENERATED_LINE,
    rootName,
    packages,
    packageByName,
    filesByPackage,
    files,
    importsFrom,
    importersOf,
    callsFrom,
    declsOf,
    recordOf,
    externalsOf,
    packageEntry: (name) => manifest.packages[name],
    fileEntry: (file) => manifest.files[file],
    packageOf,
    cardPathOf: (file) => {
      const pkg = packageOf(file);
      return pkg === undefined ? undefined : cardPath(pkg, file);
    },
  };
}

/** `<file>` for top-level code, `<file>#<symbol>` for a declaration. */
function fileOfSymbol(id: string): string {
  const hash = id.indexOf("#");
  return hash === -1 ? id : id.slice(0, hash);
}

/**
 * Every markdown artifact, keyed by path relative to `.greplost/`. Insertion
 * order is fixed (INDEX, repo docs, then packages by path, each with its map,
 * API and cards) so two renders of the same snapshot produce identical maps
 * down to iteration order.
 */
export function renderArtifacts(input: RenderInput): Map<string, string> {
  const ctx = createContext(input);
  const out = new Map<string, string>();

  out.set("INDEX.md", buildIndex(ctx));
  out.set("repo/MAP.md", buildRepoMap(ctx));
  out.set("repo/HOTSPOTS.md", buildHotspots(ctx));

  for (const pkg of ctx.packages) {
    const dir = packageDir(pkg.name);
    out.set(`${dir}/MAP.md`, buildPackageMap(ctx, pkg));
    out.set(`${dir}/API.md`, buildApi(ctx, pkg));
    for (const file of ctx.filesByPackage.get(pkg.name) ?? []) {
      out.set(cardPath(pkg, file), buildCard(ctx, file));
    }
  }

  return out;
}

export function renderIndex(input: RenderInput): string {
  return buildIndex(createContext(input));
}

export function renderRepoMap(input: RenderInput): string {
  return buildRepoMap(createContext(input));
}

export function renderHotspots(input: RenderInput): string {
  return buildHotspots(createContext(input));
}

export function renderPackageMap(input: RenderInput, pkg: PackageInfo): string {
  return buildPackageMap(createContext(input), pkg);
}

export function renderApi(input: RenderInput, pkg: PackageInfo): string {
  return buildApi(createContext(input), pkg);
}

export function renderCard(input: RenderInput, file: string): string {
  return buildCard(createContext(input), file);
}
