/**
 * greplost:render document assembly (render spec "Documents", tech spec 4.2/4.3).
 *
 * `renderArtifacts` turns one `Snapshot` plus its `SummaryCache` into every
 * markdown artifact under `.greplost/`, keyed by artifact-relative path. Pure:
 * no filesystem access, no `Date`, no environment, no absolute paths — the
 * only date that ever reaches the output is the `refreshedAt` of a semantic
 * summary, and only inside the staleness banner (tech spec 5.3, 6).
 *
 * The per-document renderers all take the same `RenderInput` and are exported
 * for callers that want one artifact; `renderArtifacts` builds the shared
 * `DocContext` once and reuses it, so a full render stays linear in the number
 * of files rather than quadratic.
 *
 * Module layout: this file owns the context and the public surface; the six
 * `docs/*.ts` modules own one document each and depend on this file for types
 * only (`import type`), which keeps the runtime import graph acyclic.
 */

import type {
  CallEdge,
  Declaration,
  FileEntry,
  FileRecord,
  GreplostConfig,
  ImportEdge,
  Manifest,
  PackageEntry,
  PackageInfo,
  ReferenceEdge,
  Snapshot,
  SummaryCache,
} from "@greplost/core/schema";
import { compareEdges, compareStrings, isFileId, isNodeKind, splitNodeId } from "@greplost/core/schema";
import { blastRadius, filesByDirectory, impactPairs } from "@greplost/core/graph";

import { cardPath, nodeCardPath, packageDir } from "./slug.ts";
import { buildNodeCard } from "./docs/node-card.ts";
import { buildIndex } from "./docs/index-doc.ts";
import { buildRepoMap } from "./docs/repo-map.ts";
import { buildHotspots } from "./docs/hotspots.ts";
import { buildPackageMap } from "./docs/package-map.ts";
import { buildApi } from "./docs/api.ts";
import { buildCard } from "./docs/card.ts";

export interface RenderInput {
  snapshot: Snapshot;
  summaries: SummaryCache;
}

/** The generated-by line every artifact carries under its level-1 title. */
export const GENERATED_LINE = "> Generated by greplost. Do not edit by hand; run `greplost update`.";

/**
 * Everything the document renderers need, indexed once. Held by value so a
 * document renderer is a pure function of `(ctx, target)` and never walks the
 * whole snapshot to answer a per-file question.
 */
export interface DocContext {
  snapshot: Snapshot;
  summaries: SummaryCache;
  config: GreplostConfig;
  manifest: Manifest;
  /** Copied here so the docs modules never import a value from this file. */
  generatedLine: string;
  /** Name of the package rooted at ".", or the repo's own directory-less fallback. */
  rootName: string;
  /** Every package, sorted by path. */
  packages: PackageInfo[];
  /**
   * Packages with at least one indexed file, sorted by path. A package with no
   * indexed files keeps its INDEX table row but is left out of the ASCII
   * package tree and the container diagram, where it would be a dead branch and
   * an isolated node (render spec, GitHub rendering rule).
   */
  indexedPackages: PackageInfo[];
  packageByName: Map<string, PackageInfo>;
  /** Repo-relative file paths, sorted, per package name. */
  filesByPackage: Map<string, string[]>;
  /** Every repo file path, sorted. */
  files: string[];
  /** Import/re-export edges leaving a file, in snapshot order. */
  importsFrom: Map<string, ImportEdge[]>;
  /** Distinct repo files importing a file, sorted. */
  importersOf: Map<string, string[]>;
  /** Call edges leaving a file (from the file itself or any symbol in it). */
  callsFrom: Map<string, CallEdge[]>;
  /** Declarations of a file, in line order. */
  declsOf: Map<string, Declaration[]>;
  /**
   * Schema 2: the non-file nodes a file declares, span-sorted. Only files that
   * have at least one are keyed, so `size === 0` is exactly "this repo has no
   * nodes" and every node-aware block can be skipped in one test.
   */
  nodesOf: Map<string, Declaration[]>;
  /** Every declaration by id, so a reference target can be named and linked. */
  declById: Map<string, Declaration>;
  /** Reference edges leaving an id, sorted by target. */
  referencesFrom: Map<string, ReferenceEdge[]>;
  /** Reference edges arriving at an id, sorted by source. */
  referencesTo: Map<string, ReferenceEdge[]>;
  /**
   * Reverse-closure size over `impactPairs` per node id: the number a node card
   * prints and the number `greplost impact <node-id>` prints, by construction.
   * Empty for a repo with no nodes, which is what keeps that repo's render free.
   */
  nodeBlast: Map<string, number>;
  /** The extracted record of a file, when the snapshot carries one. */
  recordOf: Map<string, FileRecord>;
  /** Distinct external package names imported by a package, sorted. */
  externalsOf: Map<string, string[]>;
  packageEntry(name: string): PackageEntry | undefined;
  fileEntry(file: string): FileEntry | undefined;
  packageOf(file: string): PackageInfo | undefined;
  /** Artifact path of a file's module card, or undefined when the file is unknown. */
  cardPathOf(file: string): string | undefined;
  /**
   * Artifact path of a non-file node's card, or undefined when `id` is not a
   * node id or its file belongs to no package.
   */
  nodeCardPathOf(id: string): string | undefined;
}

/**
 * The id universe a node's blast pass runs over: every indexed file, every node
 * id, and every endpoint of an `impactPairs` pair. Sorted and deduplicated.
 *
 * Plain symbols are deliberately absent. `blastRadius` allocates one bitset row
 * of `ceil(V / 32)` words per strongly connected component, so the universe is
 * quadratic in its own size — seeding it with `declById` (every declaration in
 * the repo) cost about V^2 / 8 bytes, roughly 800 MB on an 80k-declaration
 * checkout, to compute closures for ids that no import, re-export or reference
 * pair can ever name. A symbol reaches a card through `callsFrom`, never here.
 */
export function blastUniverse(
  files: readonly string[],
  nodeIds: Iterable<string>,
  pairs: ReadonlyArray<readonly [string, string]>,
): string[] {
  const ids = new Set<string>(files);
  for (const id of nodeIds) ids.add(id);
  for (const [from, to] of pairs) {
    ids.add(from);
    ids.add(to);
  }
  return [...ids].sort(compareStrings);
}

/** Builds the shared index. Cheap enough to call per document, linear in the snapshot. */
export function createContext(input: RenderInput): DocContext {
  const { snapshot } = input;
  const manifest = snapshot.manifest;

  const packages = [...snapshot.packages].sort((a, b) => compareStrings(a.path, b.path));
  const packageByName = new Map<string, PackageInfo>();
  for (const pkg of snapshot.packages) packageByName.set(pkg.name, pkg);

  const rootName = packages.find((p) => p.path === ".")?.name ?? packages[0]?.name ?? "repo";

  const files = Object.keys(manifest.files).sort(compareStrings);
  const filesByPackage = new Map<string, string[]>();
  for (const pkg of packages) filesByPackage.set(pkg.name, []);
  for (const file of files) {
    const pkgName = manifest.files[file]?.pkg;
    if (pkgName === undefined) continue;
    const bucket = filesByPackage.get(pkgName);
    if (bucket) bucket.push(file);
    else filesByPackage.set(pkgName, [file]);
  }

  const importsFrom = new Map<string, ImportEdge[]>();
  const importerSets = new Map<string, Set<string>>();
  const externalSets = new Map<string, Set<string>>();
  // The indexed files an import target reaches. A Go import names a package, so
  // its target is a *directory* and it imports every indexed file in it (tech
  // spec Appendix C); a file target is just itself, which leaves every
  // TypeScript card unchanged. Same rule as `expandDirectoryTargets` in the
  // graph layer, which is where fan-in and blast radius get it from.
  const filesInDirectory = filesByDirectory(files);
  const importReaches = (to: string): readonly string[] =>
    manifest.files[to] !== undefined && isFileId(to) ? [to] : (filesInDirectory.get(to) ?? []);
  for (const edge of snapshot.imports) {
    const bucket = importsFrom.get(edge.from);
    if (bucket) bucket.push(edge);
    else importsFrom.set(edge.from, [edge]);

    for (const target of importReaches(edge.to)) {
      if (target === edge.from) continue;
      const importers = importerSets.get(target);
      if (importers) importers.add(edge.from);
      else importerSets.set(target, new Set([edge.from]));
    }

    if (edge.to.startsWith("ext:")) {
      const pkgName = manifest.files[edge.from]?.pkg;
      if (pkgName !== undefined) {
        const externals = externalSets.get(pkgName);
        if (externals) externals.add(edge.to.slice("ext:".length));
        else externalSets.set(pkgName, new Set([edge.to.slice("ext:".length)]));
      }
    }
  }
  const importersOf = new Map<string, string[]>();
  for (const [file, importers] of importerSets) {
    importersOf.set(file, [...importers].sort(compareStrings));
  }
  const externalsOf = new Map<string, string[]>();
  for (const pkg of packages) externalsOf.set(pkg.name, []);
  for (const [pkgName, externals] of externalSets) {
    externalsOf.set(pkgName, [...externals].sort(compareStrings));
  }

  const callsFrom = new Map<string, CallEdge[]>();
  for (const call of snapshot.calls) {
    const file = fileOfSymbol(call.from);
    const bucket = callsFrom.get(file);
    if (bucket) bucket.push(call);
    else callsFrom.set(file, [call]);
  }

  // Copied, never sorted in place: the snapshot is an input and must survive a
  // render unchanged (the determinism tests render the same object twice).
  const declsOf = new Map<string, Declaration[]>();
  const recordOf = new Map<string, FileRecord>();
  for (const record of snapshot.files) {
    recordOf.set(record.path, record);
    declsOf.set(record.path, [...record.decls]);
  }
  // A snapshot whose `symbols` cover a file with no `FileRecord` (a partial or
  // reconstructed snapshot) still gets a card.
  for (const decl of snapshot.symbols) {
    if (recordOf.has(decl.file)) continue;
    const bucket = declsOf.get(decl.file);
    if (bucket) bucket.push(decl);
    else declsOf.set(decl.file, [decl]);
  }
  for (const decls of declsOf.values()) {
    decls.sort((a, b) => a.span[0] - b.span[0] || compareStrings(a.id, b.id));
  }

  // Schema 2. Every map below is empty for a repo with no non-file nodes, and
  // every block that reads one is skipped when it is, so such a repo renders
  // exactly the bytes build 1 rendered (spec 4.4, "no nodes no change").
  const declById = new Map<string, Declaration>();
  const nodesOf = new Map<string, Declaration[]>();
  for (const decls of declsOf.values()) {
    for (const decl of decls) {
      declById.set(decl.id, decl);
      if (!isNodeKind(decl.kind)) continue;
      const bucket = nodesOf.get(decl.file);
      if (bucket) bucket.push(decl);
      else nodesOf.set(decl.file, [decl]);
    }
  }

  const references = snapshot.references ?? [];
  const referencesFrom = new Map<string, ReferenceEdge[]>();
  const referencesTo = new Map<string, ReferenceEdge[]>();
  for (const edge of references) {
    const from = referencesFrom.get(edge.from);
    if (from) from.push(edge);
    else referencesFrom.set(edge.from, [edge]);
    const to = referencesTo.get(edge.to);
    if (to) to.push(edge);
    else referencesTo.set(edge.to, [edge]);
  }
  for (const bucket of referencesFrom.values()) bucket.sort(compareEdges);
  for (const bucket of referencesTo.values()) bucket.sort(compareEdges);

  const packageOf = (file: string): PackageInfo | undefined => {
    const pkgName = manifest.files[file]?.pkg;
    return pkgName === undefined ? undefined : packageByName.get(pkgName);
  };

  const indexedPackages = packages.filter((pkg) => (filesByPackage.get(pkg.name) ?? []).length > 0);

  // One reverse-closure pass over the whole mixed graph rather than one blast
  // walk per node: a Terraform monorepo has thousands of nodes, and per-card
  // `impactOf` would make a render quadratic in them.
  const nodeBlast = new Map<string, number>();
  const nodeIds: string[] = [];
  for (const bucket of nodesOf.values()) for (const decl of bucket) nodeIds.push(decl.id);
  if (nodeIds.length > 0) {
    const pairs = impactPairs({
      manifest,
      imports: snapshot.imports,
      calls: snapshot.calls,
      symbols: snapshot.symbols,
      references,
    });
    const radiusById = blastRadius(blastUniverse(files, nodeIds, pairs), pairs);
    for (const id of nodeIds) nodeBlast.set(id, radiusById.get(id) ?? 0);
  }

  const nodeCardPathOf = (id: string): string | undefined => {
    const parts = splitNodeId(id);
    if (parts === null) return undefined;
    const pkg = packageOf(parts.file);
    return pkg === undefined ? undefined : nodeCardPath(pkg, id);
  };

  return {
    snapshot,
    summaries: input.summaries,
    config: snapshot.config,
    manifest,
    generatedLine: GENERATED_LINE,
    rootName,
    packages,
    indexedPackages,
    packageByName,
    filesByPackage,
    files,
    importsFrom,
    importersOf,
    callsFrom,
    declsOf,
    nodesOf,
    declById,
    referencesFrom,
    referencesTo,
    nodeBlast,
    recordOf,
    externalsOf,
    packageEntry: (name) => manifest.packages[name],
    fileEntry: (file) => manifest.files[file],
    packageOf,
    cardPathOf: (file) => {
      const pkg = packageOf(file);
      return pkg === undefined ? undefined : cardPath(pkg, file);
    },
    nodeCardPathOf,
  };
}

/** `<file>` for top-level code, `<file>#<symbol>` for a declaration. */
function fileOfSymbol(id: string): string {
  const hash = id.indexOf("#");
  return hash === -1 ? id : id.slice(0, hash);
}

/**
 * Every markdown artifact, keyed by path relative to `.greplost/`. Insertion
 * order is fixed (INDEX, repo docs, then packages by path, each with its map,
 * API and cards) so two renders of the same snapshot produce identical maps
 * down to iteration order.
 */
export function renderArtifacts(input: RenderInput): Map<string, string> {
  const ctx = createContext(input);
  assertNoSlugCollision(ctx.packages);
  const out = new Map<string, string>();
  // Every path the render claimed, in emission order and *with* duplicates: a
  // Map silently keeps the last writer, so the guard needs the raw list.
  const claimed: string[] = [];
  const emit = (path: string, text: string): void => {
    claimed.push(path);
    out.set(path, text);
  };

  emit("INDEX.md", buildIndex(ctx));
  emit("repo/MAP.md", buildRepoMap(ctx));
  emit("repo/HOTSPOTS.md", buildHotspots(ctx));

  for (const pkg of ctx.packages) {
    const dir = packageDir(pkg.name);
    emit(`${dir}/MAP.md`, buildPackageMap(ctx, pkg));
    emit(`${dir}/API.md`, buildApi(ctx, pkg));
    for (const file of ctx.filesByPackage.get(pkg.name) ?? []) {
      emit(cardPath(pkg, file), buildCard(ctx, file));
      // Each of the file's non-file nodes, immediately after its file card, so
      // the artifact order is still "package by path, each file in path order".
      for (const decl of ctx.nodesOf.get(file) ?? []) {
        emit(nodeCardPath(pkg, decl.id), buildNodeCard(ctx, decl.id));
      }
    }
  }

  assertNoCardCollision(claimed);
  return out;
}

/**
 * `packageSlug` is not injective (`@a/b` and `a__b` both slug to `a__b`), and a
 * collision would silently overwrite one package's whole artifact directory
 * with another's. Checked in package-name order so the message is stable.
 */
function assertNoSlugCollision(packages: readonly PackageInfo[]): void {
  const seen = new Map<string, string>();
  for (const pkg of [...packages].sort((a, b) => compareStrings(a.name, b.name))) {
    const dir = packageDir(pkg.name);
    const other = seen.get(dir);
    if (other !== undefined) {
      throw new Error(`greplost: package slug collision: ${other} and ${pkg.name} both map to ${dir}`);
    }
    seen.set(dir, pkg.name);
  }
}

/**
 * `nodeSlug` is lossy (`a/b` and `a__b` both slug to `a__b`), and a node card
 * directory is named after a file, so two artifacts can in principle claim one
 * path. Silently keeping the last writer would lose a card and leave its
 * inbound links pointing at another node's page, so this is a hard failure.
 * Checked in path order, and the message names both paths, so it is actionable.
 *
 * Paths are compared **case-folded and NFC-normalised**, because the filesystem
 * the map is written to does the same. `resource "aws_vpc" "Main"` beside
 * `resource "aws_vpc" "main"` is legal Terraform and two distinct ids, but one
 * file on APFS and NTFS; so is a composed `café.tf` beside a decomposed one.
 * An exact-string check passes, the second card silently overwrites the first,
 * and `greplost verify` is then red on every run with nothing the user can do
 * about it. The comparison is folded; the artifact is still written under the
 * path the id produced.
 */
function assertNoCardCollision(paths: readonly string[]): void {
  const seen = new Map<string, string>();
  for (const path of [...paths].sort(compareStrings)) {
    // `toLowerCase`, not `toLocaleLowerCase`: a render must not depend on the
    // machine's locale (Turkish dotless i would fold two different paths here
    // and not on the next machine).
    const folded = path.normalize("NFC").toLowerCase();
    const other = seen.get(folded);
    if (other === path) {
      throw new Error(`greplost: card path collision: two artifacts both claim ${path}`);
    }
    if (other !== undefined) {
      throw new Error(
        `greplost: card path collision: ${other} and ${path} differ only by case or Unicode ` +
          "normalisation, and are one file on a case-insensitive filesystem",
      );
    }
    seen.set(folded, path);
  }
}

export function renderIndex(input: RenderInput): string {
  return buildIndex(createContext(input));
}

export function renderRepoMap(input: RenderInput): string {
  return buildRepoMap(createContext(input));
}

export function renderHotspots(input: RenderInput): string {
  return buildHotspots(createContext(input));
}

export function renderPackageMap(input: RenderInput, pkg: PackageInfo): string {
  return buildPackageMap(createContext(input), pkg);
}

export function renderApi(input: RenderInput, pkg: PackageInfo): string {
  return buildApi(createContext(input), pkg);
}

export function renderCard(input: RenderInput, file: string): string {
  return buildCard(createContext(input), file);
}

/** One non-file node's card (schema 2); throws when `id` is not a node this map declares. */
export function renderNodeCard(input: RenderInput, id: string): string {
  return buildNodeCard(createContext(input), id);
}
